# "debug" or "production"
BUILD_TYPE = production

include ../../include/standard_definitions.mk

PROG1 = TestReal.e
SRCS1 = TestReal.cpp
OBJS1 = TestReal.o

PROG2 = TestComplex.e
SRCS2 = TestComplex.cpp
OBJS2 = TestComplex.o

PROG3 = simple_test.e
SRCS3 = simple_test.cpp
OBJS3 = simple_test.o


include ../../include/standard_makes.mk