# "debug" or "production"
BUILD_TYPE = production

include ../../../include/standard_definitions.mk

PROG0 = GrapeUnitary1.e
SRCS0 = GrapeUnitary1.cpp
OBJS0 = GrapeUnitary1.o

PROG1 = GrapeUnitary2.e
SRCS1 = GrapeUnitary2.cpp
OBJS1 = GrapeUnitary2.o

PROG2 = GrapeUnitary3.e
SRCS2 = GrapeUnitary3.cpp
OBJS2 = GrapeUnitary3.o

PROG3 = GrapeUnitary4.e
SRCS3 = GrapeUnitary4.cpp
OBJS3 = GrapeUnitary4.o

include ../../../include/standard_makes.mk
