# "debug" or "production"
BUILD_TYPE = debug

include ../../include/standard_definitions.mk

PROG1 = TestReal.e
SRCS1 = TestReal.cpp
OBJS1 = TestReal.o

PROG2 = TestComplex.e
SRCS2 = TestComplex.cpp
OBJS2 = TestComplex.o

PROG3 = TestAssignment.e
SRCS3 = TestAssignment.cpp
OBJS3 = TestAssignment.o

include ../../include/standard_makes.mk