# "debug" or "production"
BUILD_TYPE = debug

include ../../include/standard_definitions.mk

OBJS0 = NumericalLimits.o
PROG0 = NumericalLimits.e
SRCS0 = NumericalLimits.cpp

include ../../include/standard_makes.mk