# "debug" or "production"
BUILD_TYPE = debug

include ../../include/standard_definitions.mk

OBJS1 = TestUtil.o
PROG1 = TestUtil.e
SRCS1 = TestUtil.cpp

OBJS2 = TestPolar.o
PROG2 = TestPolar.e
SRCS2 = TestPolar.cpp

OBJS3 = Pulses.o
PROG3 = Pulses.e
SRCS3 = Pulses.cpp

include ../../include/standard_makes.mk