# "debug" or "production"
BUILD_TYPE = production

include ../../include/standard_definitions.mk

PROG0 = GrapeState.e
SRCS0 = GrapeState.cpp
OBJS0 = GrapeState.o

PROG1 = GrapeState1.e
SRCS1 = GrapeState1.cpp
OBJS1 = GrapeState1.o

PROG2 = GrapeUnitary1.e
SRCS2 = GrapeUnitary1.cpp
OBJS2 = GrapeUnitary1.o

PROG3 = CompareEvolutions2.e
SRCS3 = CompareEvolutions2.cpp
OBJS3 = CompareEvolutions2.o

PROG4 = GrapeEnvelopeCompare.e
SRCS4 = GrapeEnvelopeCompare.cpp
OBJS4 = GrapeEnvelopeCompare.o

PROG5 = GrapeUnitaryEnvelope.e
SRCS5 = GrapeUnitaryEnvelope.cpp
OBJS5 = GrapeUnitaryEnvelope.o

PROG8 = CompareEvolutions.e
SRCS8 = CompareEvolutions.cpp
OBJS8 = CompareEvolutions.o

SRCS6 = Benchmark.cpp
PROG6 = Benchmark.e
OBJS6 = Benchmark.o

#SRCS7 = GrapeSweepAmps2.cpp
#PROG7 = GrapeSweepAmps2.e
#OBJS7 = GrapeSweepAmps2.o

PROG7 = GrapeSelect.e
SRCS7 = GrapeSelect.cpp
OBJS7 = GrapeSelect.o



include ../../include/standard_makes.mk
