# "debug" or "production"
BUILD_TYPE = debug

include ../../../include/standard_definitions.mk

PROG0 = CompareEvolutions.e
SRCS0 = CompareEvolutions.cpp
OBJS0 = CompareEvolutions.o

PROG1 = CompareLabEnvelopes.e
SRCS1 = CompareLabEnvelopes.cpp
OBJS1 = CompareLabEnvelopes.o

PROG2 = CompareEvolutions2.e
SRCS2 = CompareEvolutions2.cpp
OBJS2 = CompareEvolutions2.o

PROG3 = CompareEvolutions3.e
SRCS3 = CompareEvolutions3.cpp
OBJS3 = CompareEvolutions3.o

PROG4 = AWG.e
SRCS4 = AWG.cpp
OBJS4 = AWG.o

#

include ../../../include/standard_makes.mk
