# "debug" or "production"
BUILD_TYPE = debug

include ../../../include/standard_definitions.mk

OBJS1 = TestMasterCavity.o
PROG1 = TestMasterCavity.e
SRCS1 = TestMasterCavity.cpp

include ../../../include/standard_makes.mk