# "debug" or "production"
BUILD_TYPE = production

include ../../../include/standard_definitions.mk

PROG0 = LandauZener.e
SRCS0 = LandauZener.cpp
OBJS0 = LandauZener.o

PROG1 = cosineansatz.e
SRCS1 = cosineansatz.cpp
OBJS1 = cosineansatz.o

include ../../../include/standard_makes.mk
