# "debug" or "production"
BUILD_TYPE = debug

include ../../../include/standard_definitions.mk

OBJS0 = TestEuler.o
PROG0 = TestEuler.e
SRCS0 = TestEuler.cpp

OBJS1 = TestRombergEuler.o
PROG1 = TestRombergEuler.e
SRCS1 = TestRombergEuler.cpp

OBJS2 = TestRK4.o
PROG2 = TestRK4.e
SRCS2 = TestRK4.cpp

OBJS3 = TestRombergRK4.o
PROG3 = TestRombergRK4.e
SRCS3 = TestRombergRK4.cpp

OBJS4 = TestAdapEuler.o
PROG4 = TestAdapEuler.e
SRCS4 = TestAdapEuler.cpp

OBJS5 = TestAdapRK4.o
PROG5 = TestAdapRK4.e
SRCS5 = TestAdapRK4.cpp

OBJS6 = TestAdapRK45.o
PROG6 = TestAdapRK45.e
SRCS6 = TestAdapRK45.cpp

OBJS7 = TestAdapRKCK.o
PROG7 = TestAdapRKCK.e
SRCS7 = TestAdapRKCK.cpp


include ../../../include/standard_makes.mk