# "debug" or "production"
BUILD_TYPE = production

include ../../../include/standard_definitions.mk

PROG0 = CoherentCavity.e
SRCS0 = CoherentCavity.cpp
OBJS0 = CoherentCavity.o

include ../../../include/standard_makes.mk
