# "debug" or "production"
BUILD_TYPE = debug

include ../../include/standard_definitions.mk

PROG0 = LAPACK_dgesv.e
SRCS0 = LAPACK_dgesv.cpp
OBJS0 = LAPACK_dgesv.o

PROG1 = LAPACK_dgeev.e
SRCS1 = LAPACK_dgeev.cpp
OBJS1 = LAPACK_dgeev.o

PROG2 = LAPACK_dsyev.e
SRCS2 = LAPACK_dsyev.cpp
OBJS2 = LAPACK_dsyev.o

PROG3 = LAPACK_zgeev.e
SRCS3 = LAPACK_zgeev.cpp
OBJS3 = LAPACK_zgeev.o

PROG4 = LAPACK_zheev.e
SRCS4 = LAPACK_zheev.cpp
OBJS4 = LAPACK_zheev.o

PROG5 = LAPACK_zheevr.e
SRCS5 = LAPACK_zheevr.cpp
OBJS5 = LAPACK_zheevr.o

include ../../include/standard_makes.mk