# "debug" or "production"
BUILD_TYPE = debug

include ../../include/standard_definitions.mk

PROG0 = NumericalIntegrationTest.e
SRCS0 = NumericalIntegrationTest.cpp
OBJS0 = NumericalIntegrationTest.o

include ../../include/standard_makes.mk
