# "debug" or "production"
BUILD_TYPE = production

include ../../include/standard_definitions.mk

PROG1 = TestExpectation.e
SRCS1 = TestExpectation.cpp
OBJS1 = TestExpectation.o

PROG2 = TestCavity.e
SRCS2 = TestCavity.cpp
OBJS2 = TestCavity.o

PROG3 = TestQubits.e
SRCS3 = TestQubits.cpp
OBJS3 = TestQubits.o

PROG4 = TestSuperHami.e
SRCS4 = TestSuperHami.cpp
OBJS4 = TestSuperHami.o

PROG5 = TestSuperDamp.e
SRCS5 = TestSuperDamp.cpp
OBJS5 = TestSuperDamp.o

PROG6 = TestSupers.e
SRCS6 = TestSupers.cpp
OBJS6 = TestSupers.o

include ../../include/standard_makes.mk