# "debug" or "production"
BUILD_TYPE = debug

include ../../include/standard_definitions.mk

PROG1 = TestReal.e
SRCS1 = TestReal.cpp
OBJS1 = TestReal.o

PROG2 = TestComplex.e
SRCS2 = TestComplex.cpp
OBJS2 = TestComplex.o

PROG3 = PauliGellMann.e
SRCS3 = PauliGellMann.cpp
OBJS3 = PauliGellMann.o

PROG5 = CavityOperators.e
SRCS5 = CavityOperators.cpp
OBJS5 = CavityOperators.o

include ../../include/standard_makes.mk


