# "debug" or "production"
BUILD_TYPE = debug

include ../../../include/standard_definitions.mk

OBJS1 = TestMasterRK45.o
PROG1 = TestMasterRK45.e
SRCS1 = TestMasterRK45.cpp

OBJS2 = TestMasterRKCK.o
PROG2 = TestMasterRKCK.e
SRCS2 = TestMasterRKCK.cpp

include ../../../include/standard_makes.mk