# "debug" or "production"
BUILD_TYPE = debug

include ../../../include/standard_definitions.mk

OBJS1 = TwoQubitXY.o
PROG1 = TwoQubitXY.e
SRCS1 = TwoQubitXY.cpp

include ../../../include/standard_makes.mk