# "debug" or "production"
BUILD_TYPE = production

include ../../include/standard_definitions.mk

PROG0 = TestCppExp.e
SRCS0 = TestCppExp.cpp
OBJS0 = TestCppExp.o

PROG1 = TestHermitian.e
SRCS1 = TestHermitian.cpp
OBJS1 = TestHermitian.o

PROG2 = TestHermitian2.e
SRCS2 = TestHermitian2.cpp
OBJS2 = TestHermitian2.o

PROG3 = TestSymmetric.e
SRCS3 = TestSymmetric.cpp
OBJS3 = TestSymmetric.o

PROG4 = TestSymmetric2.e
SRCS4 = TestSymmetric2.cpp
OBJS4 = TestSymmetric2.o

include ../../include/standard_makes.mk