# "debug" or "production"
BUILD_TYPE = debug

include ../../../include/standard_definitions.mk

OBJS1 = TestComplexRK45.o
PROG1 = TestComplexRK45.e
SRCS1 = TestComplexRK45.cpp

include ../../../include/standard_makes.mk