# "debug" or "production"
BUILD_TYPE = debug

include ../../include/standard_definitions.mk

OBJS1 = TestSpecialFunctions.o
PROG1 = TestSpecialFunctions.e
SRCS1 = TestSpecialFunctions.cpp

OBJS2 = TestErrorFunction.o
PROG2 = TestErrorFunction.e
SRCS2 = TestErrorFunction.cpp

include ../../include/standard_makes.mk