# "debug" or "production"
BUILD_TYPE = production

include ../../../include/standard_definitions.mk

PROG0 = TwoCavity.e
SRCS0 = TwoCavity.cpp
OBJS0 = TwoCavity.o


include ../../../include/standard_makes.mk
